# Generated by Django 4.1.13 on 2023-11-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='tag',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Clubs & Chapters', 'Clubs & Chapters'), ('event', 'Events'), ('Placement', 'Placement'), ('Scholarship', 'Scholarship'), ('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Other', 'Other')], max_length=100),
        ),
    ]
