# Generated by Django 4.1.13 on 2023-11-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_alter_announcement_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='date',
            new_name='eventDate',
        ),
    ]
