# Generated by Django 4.2.6 on 2023-11-15 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_alter_announcement_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
