# Generated by Django 4.2.6 on 2023-11-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_announcement_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='tag',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Clubs & Chapters', 'Clubs & Chapters'), ('Events', 'Events'), ('Placement', 'Placement'), ('Scholarship', 'Scholarship'), ('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Other', 'Other')], max_length=100),
        ),
    ]
